dictionary/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'entry/(?P<pk>\d+)/', views.EntryView.as_view(), name='entry'),
    url(r'search/', views.SearchAny.as_view(), name='search'),
]

hanyu/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.Home.as_view(), name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^dictionary/', include('dictionary.urls', namespace='dictionary')),
    url(r'^learning/', include('learning_tools.urls', namespace='learning')),
    url(r'^quiz/', include('quiz.urls', namespace='quiz')),
]

quiz/urls.py
from django.conf.urls import url

from . import views

urlpatterns =[
    url(r'quiz/$', views.QuizView.as_view(), name='quiz'),
    # url(r'json/$', views.QuizJSON.as_view(), name='json'),
    url(r'data/$', views.quiz_data, name='quiz_data'),
]

dictionary/forms.py
from django import forms


class SearchForm(forms.Form):
    search_text = forms.CharField(label='', max_length=255)

templates/_base.html
{% extends "_AdminLTE.html" %}
{% load AdminLTE %}
{% load static %}

{% block title %}
Hanyu |
{% endblock title %}

{% block logo_mini %}汉语{% endblock logo_mini %}
{% block logo_lg %}汉语 Hanyu{% endblock logo_lg %}

{% block messages %}
{% endblock messages %}
{% block notifications %}
{% endblock notifications %}

{% block user_menu_body %}
{% endblock user_menu_body %}

{% block search_form %}
<!-- search form (Optional) -->
<form action="{% url 'dictionary:search' %}" method="get" class="sidebar-form">
    {% csrf_token %}
    <div class="input-group">
        <input class="form-control" id="id_search_text" maxlength="255" name="search_text" type="text" required placeholder="Search...">
        <span class="input-group-btn">
            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                <i class="fa fa-search"></i>
            </button>
        </span>
    </div> 
    <div class="input-group" style="color:white">
        <label class="radio-inline"><input type="radio" name="search_type" value="0" checked>Word</label>
        <label class="radio-inline"><input type="radio" name="search_type" value="1">Segment Text</label>  
    </div>
</form>
<!-- /.search form -->
{% endblock search_form %}

{% block sidebar_menu_header %}
SITE DIRECTORY
{% endblock sidebar_menu_header %}
        
{% block page_title  %}
Hanyu Pro
{% endblock page_title  %}
{% block page_subtitle  %}
Learn Chinese with Hanyu!
{% endblock page_subtitle  %}

{% block breadcrumb %}
    <li><a href="{% url 'home' %}"><i class="fa fa-dashboard"></i> Home</a></li>
{% endblock breadcrumb %}

{% block treeview_menu %}
    {% menu_tree_open 'Accounts' %}
    {% menu_tree_item 'accounts:login' 'Login' %}  
    {% menu_tree_item 'accounts:logout' 'Logout' %} 
    {% menu_tree_item 'accounts:register' 'Register' %} 
    {% menu_tree_item 'accounts:profile' 'Profile' %}
    {% menu_tree_close %} 

    {% menu_tree_open 'Learning Tools' %}
    {% menu_tree_item 'learning:update_word_status' 'Word Status' %}
    {% menu_tree_item 'learning:word_status' 'Acquiring' 'status' 'AC' %}

    {% menu_tree_item 'learning:word_status' 'Learned' 'status' 'LN' %}
    {% menu_tree_close %}

    {% menu_tree_open 'Quiz' %}
    {% menu_tree_item 'quiz:quiz' 'Multiple Choice' %}
    {% menu_tree_close %}
{% endblock treeview_menu %}

{% block content_box %}
{% endblock content_box %}

{% block content %}
Say Hello to Hanyu
{% endblock content %}

{% block right_footer  %}
    A <a href="http://www.chipy.org">Chipy</a> Mentorship Project
{% endblock right_footer  %}

{% block left_footer %}
The Hanyu Project
{% endblock left_footer %}

{% block sidebar_toggle_button %}
{% endblock sidebar_toggle_button %}

{% block control_sidebar %}
{% endblock control_sidebar %}

{% block javascript %}
{{ block.super }}
<script>    
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    } 

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    function setupAjax(){
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken",  getCookie("csrftoken"));
                }
            }
        });
    }
</script>
{% endblock javascript %}

templates/_menu_tree_close.html
</ul>
</li>

templates/_menu_tree_item.html
<li><a href="{{ link }}"><i class="fa fa-circle-o"></i>{{ description }}</a></li>

templates/_menu_tree_open.html
    <li class="treeview">
        <a href="#">
        <i class=  "fa fa-dashboard" ></i> <span> {{ heading }} </span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
        </a>
        <ul class="treeview-menu">

templates/page.html
{% extends "_base.html" %}

{% block title  %}
    Hanyu | Base
{% endblock title %}

{% block body %}
  {% include "_header.html" %}
  {% include "_main-sidebar.html" %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      {% include "_page-header.html" with page_name="Hanyu" page_description="My Awesome Site" %} 
      {% include "_breadcrumb.html" %}
    </section>

    <!-- Main content -->
    <section class="content">
      {% block content %}
      <!-- Page Content Here -->
      {% endblock content %}
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  {% include "_footer.html" %}
  {% include "_control-sidebar.html" %}
{% endblock body %}